import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  screen_bids: {
    flex: 1,
    backgroundColor: '#1F2332',
  },
  screen_bids_title: {
    flexDirection: 'row',
    justifyContent: 'center',
    padding: 14,
    gap: 6,
  },
  screen_bids_title_text: {
    fontFamily: 'Montserrat-Bold',
    fontSize: 22,
    color: 'white',
    fontWeight: '700',
    lineHeight: 24,
  },
  screen_bids_title_image: {
    width: 24,
    height: 24,
  },
  line: {
    width: '95%',
    height: 2,
    backgroundColor: '#353946',
    alignSelf: 'center',
    borderRadius: 10,
    gap: 10,
    // marginBottom: 20,
  },
  screen_charge_top: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    padding: 12,
    gap: 6,
  },
  screen_charge_top_left: {
    width: 148,
    height: 56,
    backgroundColor: '#C7577C',
    borderRadius: 6,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
  },
  screen_charge_top_left_title: {
    fontFamily: 'Montserrat-Bold',
    color: 'white',
    fontSize: 16,
    color: 'white',
    fontWeight: '700',
  },
  screen_charge_top_left_img: {
    width: 24,
    height: 24,
  },
  screen_charge_top_right: {
    width: 233,
    height: 56,
    borderRadius: 6,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
  },
  screen_charge_top_right_title: {
    fontFamily: 'Montserrat-Bold',
    color: 'white',
    fontSize: 16,
    color: 'black',
    fontWeight: '700',
  },
  screen_charge_card: {
    backgroundColor: '#2F374B',
    marginHorizontal: 10,
    gap: 16,
    borderRadius: 24,
  },
  screen_charge_top_right_img: {
    width: 24,
    height: 24,
  },
  screen_charge_card_img: {
    backgroundColor: '#3C4868',
    padding: 8,
    gap: 10,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  screen_charge_card_img_img: {
    width: 128,
    height: 128,
    alignSelf: 'center',
  },
  screen_charge_card_title: {
    gap: 4,
    paddingHorizontal: 20,
  },
  screen_charge_card_title_title: {
    color: 'white',
    fontSize: 18,
    fontFamily: 'Montserrat-Bold',
    fontWeight: '700',
    textAlign: 'center',
  },
  screen_charge_card_title_content: {
    color: 'white',
    fontSize: 12,
    fontFamily: 'Montserrat-Regular',
    fontWeight: '400',
    padding: 5,
  },
  screen_charge_card_price: {
    backgroundColor: '#595F6F',
    borderRadius: 6,
    alignItems: 'center',
    padding: 16,
    marginHorizontal: 20,
  },
  screen_charge_card_price_top: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  screen_charge_card_price_top_text: {
    fontSize: 28,
    fontFamily: 'Montserrat-Bold',
    color: 'white',
    fontWeight: '700',
  },
  screen_charge_card_price_top_img: {
    width: 32,
    height: 32,
  },
  screen_charge_card_price_bottom: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  screen_charge_card_price_bottom_text: {
    fontSize: 12,
    fontFamily: 'Montserrat-Bold',
    color: '#ACAFB7',
    fontWeight: '700',
  },
  screen_charge_card_price_bottom_img: {
    width: 16,
    height: 16,
  },
  screen_charge_card_btnbuy: {
    backgroundColor: '#4ABF40',
    borderRadius: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    padding: 20,
    marginHorizontal: 20,
    marginBottom: 20,
  },
  screen_charge_card_btnbuy_text: {
    fontSize: 16,
    fontFamily: 'Montserrat-Bold',
    color: 'white',
    fontWeight: '700',
  },
  screen_charge_card_btnbuy_img: {
    width: 24,
    height: 24,
  },
  screen_charge_card_bid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 20,
  },
  screen_charge_card_bid_downup: {
    backgroundColor: 'white',
    width: 103.5,
    height: 56,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  screen_charge_card_bid_downup_text: {
    fontSize: 28,
    fontFamily: 'Montserrat-Bold',
    color: 'black',
    fontWeight: '700',
  },
  screen_charge_card_bid_title: {
    width: 103.5,
    height: 56,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  screen_charge_card_bid_title_text: {
    fontSize: 28,
    fontFamily: 'Montserrat-Bold',
    color: 'white',
    fontWeight: '700',
  },
  screen_charge_card_bid_title_img: {},
});
export default styles;
