import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  screen_bids: {
    flex: 1,
    backgroundColor: '#1F2332',
  },
  screen_bids_title: {
    flexDirection: 'row',
    justifyContent: 'center',
    padding: 14,
    gap: 6,
  },
  screen_bids_title_text: {
    fontFamily: 'Montserrat-Bold',
    fontSize: 22,
    color: 'white',
    fontWeight: '700',
    lineHeight: 24,
  },
  screen_bids_title_image: {
    width: 24,
    height: 24,
  },
  content_top: {
    flexDirection: 'row',
    padding: 16,
    backgroundColor: '#2F374B',
    borderRadius: 6,
    gap: 16,
    marginHorizontal: 10,
    marginBottom: 10,
  },
  content_top_img: {},
  content_top_content: {},
  content_title: {
    fontFamily: 'Montserrat-Bold',
    fontSize: 14,
    color: 'white',
    fontWeight: '700',
    marginBottom: 5,
  },
  content_text: {
    fontFamily: 'Montserrat-Regular',
    fontSize: 12,
    color: 'white',
    lineHeight: 16,
    fontWeight: '400',
  },
  form_1: {
    backgroundColor: '#2F374B',
    padding: 16,
    gap: 16,
    borderRadius: 6,
    marginHorizontal: 10,
    marginBottom: 10,
  },
  form_1_top: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  form_1_top_title: {
    flexDirection: 'row',
    gap: 8,
  },
  form_1_top_title_img: {
    width: 24,
    height: 24,
  },
  form_1_top_title_content: {
    fontFamily: 'Montserrat-Bold',
    fontSize: 18,
    color: 'white',
    fontWeight: '700',
  },
  form_1_form: {},
  form_1_form_top: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  form_1_form_top_left: {
    gap: 5,
  },
  form_1_form_top_left_text: {
    fontFamily: 'Montserrat-Bold',
    fontSize: 12,
    color: 'white',
    fontWeight: '700',
  },
  form_1_form_top_left_text_pen: {
    position: 'absolute',
    zIndex: 1,
    left: 72,
    top: 20,
    width: 36,
    height: 36,
  },
  form_1_form_top_left_text_ava: {
    width: 108,
    height: 108,
    borderRadius: 100,
  },
  form_1_form_top_right: {},
  form_1_form_top_right_input: {
    marginTop: 5,
  },
  form_1_form_top_right_input_label: {
    fontFamily: 'Montserrat-Bold',
    fontSize: 10,
    color: 'white',
    fontWeight: '700',
  },
  form_1_form_top_right_input_input: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  userIcon: {
    width: 20,
    height: 20,
    margin: 8,
    left: 2,
    position: 'absolute',
    zIndex: 1,
  },
  inputName: {
    backgroundColor: 'white',
    borderRadius: 6,
    width: 223,
    height: 36,
    gap: 8,
    marginVertical: 10,
    paddingLeft: 40,
    fontSize: 12,
    fontFamily: 'Montserrat-Regular',
    borderColor: '#56698F',
    borderWidth: 1,
  },
  pen: {
    width: 20,
    height: 20,
    margin: 8,
    right: 2,
    position: 'absolute',
    zIndex: 1,
  },
  inputName_bottom: {
    backgroundColor: 'white',
    borderRadius: 6,
    width: 360,
    height: 36,
    gap: 8,
    marginVertical: 10,
    paddingLeft: 40,
    fontSize: 12,
    fontFamily: 'Montserrat-Regular',
    borderColor: '#56698F',
    borderWidth: 1,
  },
  form_1_form_top_right_input2: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  inputName_bottom2: {
    backgroundColor: 'white',
    borderRadius: 6,
    width: 170,
    height: 36,
    gap: 8,
    marginVertical: 10,
    paddingLeft: 40,
    fontSize: 12,
    fontFamily: 'Montserrat-Regular',
    borderColor: '#56698F',
    borderWidth: 1,
  },
  inputName_bottom3: {
    backgroundColor: 'white',
    borderRadius: 6,
    width: 360,
    height: 36,
    gap: 8,
    marginVertical: 10,
    paddingLeft: 10,
    fontSize: 12,
    fontFamily: 'Montserrat-Regular',
    borderColor: '#56698F',
    borderWidth: 1,
  },
  inputName_bottom4: {
    backgroundColor: 'white',
    borderRadius: 6,
    width: 170,
    height: 36,
    gap: 8,
    marginVertical: 10,
    paddingLeft: 10,
    fontSize: 12,
    fontFamily: 'Montserrat-Regular',
    borderColor: '#56698F',
    borderWidth: 1,
  },
  form_1_form_top_right_input_label1: {
    fontFamily: 'Montserrat-Bold',
    fontSize: 10,
    color: 'red',
    fontWeight: '700',
  },
  btn_bottom: {},
  buttonGreen: {
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: '#4ABF40',
    width: 329,
    height: 56,
    borderRadius: 6,
    alignItems: 'center',
    alignSelf: 'center',
    marginVertical: 20,
    gap: 4,
  },
  buttonGreenText: {
    fontSize: 16,
    fontFamily: 'Montserrat-Bold',
    color: 'white',
  },
  line: {
    width: 329,
    height: 2,
    backgroundColor: '#353946',
    alignSelf: 'center',
    borderRadius: 10,
    gap: 10,
  },
  buttonBlue: {
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: '#56698F',
    width: 329,
    height: 56,
    borderRadius: 6,
    alignItems: 'center',
    alignSelf: 'center',
    marginVertical: 20,
    gap: 4,
  },
  navigationTop: {
    flexDirection: 'row',
    padding: 12,
    gap: 4,
    marginBottom: 10,
  },
  firstText: {
    color: '#56698F',
    fontSize: 14,
    fontFamily: 'Montserrat-Bold',
  },
  secondText: {
    color: 'white',
    fontFamily: 'Montserrat-Bold',
    fontSize: 14,
  },
});
export default styles;
