import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  bid_item: {
    borderRadius: 24,
    borderRadius: 24,
    borderColor: '#56698F',
    flexDirection: 'column',
    borderWidth: 4,
    marginLeft: 13,
    marginBottom: 13,
    backgroundColor: '#3C4868',
  },
  bid_item_title: {},
  bid_item_title_text: {
    fontFamily: 'Montserrat-Bold',
    color: 'white',
    fontSize: 12,
    textAlign: 'center',
    fontWeight: '700',
    lineHeight: 16,
    margin: 8,
  },
  bid_item_content: {
    padding: 8,
    gap: 2,
    backgroundColor: '#636D86',
    borderRadius: 6,
    width: 162.5,
    height: 68,
    alignSelf: 'center',
    marginBottom: 10,
  },
  bid_item_content_title: {
    fontFamily: 'Montserrat-Bold',
    color: 'white',
    fontSize: 10,
    textAlign: 'center',
    fontWeight: '700',
  },
  bid_item_content_price: {
    fontFamily: 'Montserrat-Bold',
    color: 'white',
    fontSize: 16,
    textAlign: 'center',
    fontWeight: '700',
  },
  bid_item_content_total: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  bid_item_content_total_text: {
    fontFamily: 'Montserrat-Bold',
    color: '#B1B6C2',
    fontSize: 10,
    textAlign: 'center',
    fontWeight: '700',
  },
  bid_item_content_total_img: {
    width: 12,
    height: 12,
  },
  bid_item_bottom: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: 'white',
    borderRadius: 20,
    width: 170,
    height: 32,
    padding: 4,
    alignSelf: 'center',
    marginBottom: 4,
    marginTop: 10,
  },
  bid_item_bottom_left: {
    fontFamily: 'Montserrat-Bold',
    fontSize: 10,
    fontWeight: '700',
    padding: 6,
    color: 'black',
  },
  bid_item_bottom_right: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    backgroundColor: '#C7577C',
    height: 24,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 4,
  },
  bid_item_bottom_right_text: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'Montserrat-Bold',
    color: 'white',
    fontWeight: '700',
  },
  bid_item_bottom_right_img: {
    width: 16,
    height: 16,
  },
  bid_item_sell: {
    padding: 8,
    gap: 2,
    backgroundColor: '#636D86',
    borderRadius: 6,
    width: 162.5,
    height: 56,
    alignSelf: 'center',
  },
  bid_item_sell_title: {
    fontFamily: 'Montserrat-Bold',
    color: 'white',
    fontSize: 10,
    textAlign: 'center',
    fontWeight: '700',
  },
  bid_item_sell_content: {
    flexDirection: 'row',
    justifyContent: 'center',
    padding: 4,
    gap: 2,
  },
  bid_item_sell_content_text: {
    fontFamily: 'Montserrat-Bold',
    color: 'white',
    fontWeight: '700',
    fontSize: 12,
  },
  bid_item_sell_content_img: {
    width: 16,
    height: 16,
  },
  bid_item_datebid: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginBottom: 10,
  },
  bid_item_date: {
    padding: 8,
    gap: 8,
    backgroundColor: '#636D86',
    borderRadius: 6,
    width: 84,
    height: 32,
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bid_item_date_img: {
    width: 16,
    height: 16,
  },
  bid_item_date_day: {
    fontFamily: 'Montserrat-Bold',
    color: 'white',
    fontSize: 10,
    textAlign: 'center',
    fontWeight: '700',
  },
  bid_item_bid: {
    padding: 8,
    gap: 12,
    backgroundColor: '#636D86',
    borderRadius: 6,
    width: 70,
    height: 32,
    alignSelf: 'center',
    flexDirection: 'row',
  },
  bid_item_bid_img: {
    width: 16,
    height: 16,
  },
  bid_item_bid_price: {
    fontFamily: 'Montserrat-Bold',
    color: 'white',
    fontWeight: '700',
    fontSize: 10,
  },
  bid_item_status: {
    paddingHorizontal: 8,
    gap: 2,
    backgroundColor: '#636D86',
    borderRadius: 6,
    width: 162.5,
    height: 24,
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  bid_item_status_title: {
    fontFamily: 'Montserrat-Bold',
    color: 'white',
    fontSize: 10,
    textAlign: 'center',
    fontWeight: '700',
  },
  bid_item_status_content: {
    flexDirection: 'row',
    gap: 4,
  },
  bid_item_status_content_text: {
    fontFamily: 'Montserrat-Bold',
    color: '#B1B6C2',
    fontSize: 10,
    textAlign: 'center',
    fontWeight: '700',
  },
  dot_status: {
    width: 6,
    height: 6,
    borderRadius: 100,
    alignSelf: 'center',
  },
  dot_status_green: {
    backgroundColor: '#33B454',
  },
  dot_status_red: {
    backgroundColor: '#EE2F2F',
  },
  bid_item_img: {},
  bid_item_img_img: {
    width: 178.5,
    height: 128,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
  },
  bid_item_uses: {
    position: 'absolute',
    width: 178.5,
    height: 60,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    zIndex: 1,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bid_item_uses_top: {
    backgroundColor: '#1F2332',
    borderRadius: 30,
    height: 28,
    width: 162.5,
    zIndex: 2,
    justifyContent: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
  },
  bid_item_uses_top_image: {
    width: 24,
    height: 24,
  },
  bid_item_uses_content: {},
  bid_item_uses_content_text: {
    fontSize: 10,
    fontWeight: '700',
    fontFamily: 'Montserrat-Bold',
    color: '#FFFFFF',
  },
  bid_item_uses_content_text2: {
    fontSize: 10,
    fontWeight: '400',
    fontFamily: 'Montserrat-Regular',
    color: '#ABB7CE',
  },
  bid_item_uses_text: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '600',
    fontFamily: 'Montserrat-Bold',
    textAlign: 'center',
    paddingVertical: 2,
  },
});

export default styles;
